name: issue

on:
  push:
    branches: ["*"]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  fetch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - run: |
          ls -lR artifacts
        shell: bash
    needs: build
